/*
 * ApiPayment API
 *
 * API for handling payments, subscriptions, invoices, and payment methods for ApiPayment services.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ApiPaymentApiController : ControllerBase
    { 
        /// <summary>
        /// Create developers overage invoices
        /// </summary>
        /// <remarks>Create invoices for developers&#x27; overage based on configured product overage rules.</remarks>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/CreateDevelopersOverageInvoices")]
        [ValidateModelState]
        [SwaggerOperation("CreateDevelopersOverageInvoices")]
        public virtual IActionResult CreateDevelopersOverageInvoices()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Create a subscription
        /// </summary>
        /// <remarks>Create a new subscription with the provided subscription request details.</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/Subscription")]
        [ValidateModelState]
        [SwaggerOperation("CreateSubscription")]
        public virtual IActionResult CreateSubscription([FromBody]SubscriptionRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Cancel subscription as admin
        /// </summary>
        /// <remarks>Cancel a subscription as an administrator identified by stripeSubscriptionId.</remarks>
        /// <param name="stripeSubscriptionId"></param>
        /// <response code="200">Success</response>
        [HttpDelete]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/CancelSubscriptionAdmin")]
        [ValidateModelState]
        [SwaggerOperation("DeleteCancelSubscriptionAdmin")]
        public virtual IActionResult DeleteCancelSubscriptionAdmin([FromQuery][Required()]string stripeSubscriptionId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Cancel enterprise subscription as admin
        /// </summary>
        /// <remarks>Cancel an enterprise subscription as an administrator.</remarks>
        /// <param name="subscriptionId"></param>
        /// <param name="adminEmail"></param>
        /// <response code="200">Success</response>
        [HttpDelete]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/Enterprise/CancelSubscriptionAdmin")]
        [ValidateModelState]
        [SwaggerOperation("DeleteEnterpriseCancelSubscriptionAdmin")]
        public virtual IActionResult DeleteEnterpriseCancelSubscriptionAdmin([FromQuery][Required()]int? subscriptionId, [FromQuery][Required()]string adminEmail)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get customer payment methods by email
        /// </summary>
        /// <remarks>Retrieve payment methods associated with a customer email.</remarks>
        /// <param name="email"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/CustomerPaymentMethods")]
        [ValidateModelState]
        [SwaggerOperation("GetCustomerPaymentMethods")]
        public virtual IActionResult GetCustomerPaymentMethods([FromQuery][Required()]string email)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Delete a customer payment method
        /// </summary>
        /// <remarks>Delete a customer payment method identified by paymentMethodId.</remarks>
        /// <param name="paymentMethodId"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/DeleteCustomerPaymentMethod")]
        [ValidateModelState]
        [SwaggerOperation("GetDeleteCustomerPaymentMethod")]
        public virtual IActionResult GetDeleteCustomerPaymentMethod([FromQuery][Required()]string paymentMethodId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get downgrade options for a product and price
        /// </summary>
        /// <remarks>Retrieve available downgrade options for the specified product and price.</remarks>
        /// <param name="productId"></param>
        /// <param name="priceId"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/DowngradeOptions")]
        [ValidateModelState]
        [SwaggerOperation("GetDowngradeOptions")]
        public virtual IActionResult GetDowngradeOptions([FromQuery][Required()]string productId, [FromQuery][Required()]string priceId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get enterprise developer subscriptions
        /// </summary>
        /// <remarks>Retrieve enterprise developer subscriptions filtered by email or developer ID.</remarks>
        /// <param name="email"></param>
        /// <param name="developerId"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/GetEnterpriseDeveloperSubscriptions")]
        [ValidateModelState]
        [SwaggerOperation("GetEnterpriseDeveloperSubscriptions")]
        public virtual IActionResult GetEnterpriseDeveloperSubscriptions([FromQuery]string email, [FromQuery]int? developerId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get enterprise-tier products
        /// </summary>
        /// <remarks>Retrieve enterprise-tier products available in ApiPayment.</remarks>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/EnterpriseProducts")]
        [ValidateModelState]
        [SwaggerOperation("GetEnterpriseProducts")]
        public virtual IActionResult GetEnterpriseProducts()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get health status of the ApiPayment service
        /// </summary>
        /// <remarks>Returns service health status.</remarks>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/Health")]
        [ValidateModelState]
        [SwaggerOperation("GetHealth")]
        public virtual IActionResult GetHealth()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get product overage configuration
        /// </summary>
        /// <remarks>Retrieve the product overage configuration for a specified product.</remarks>
        /// <param name="productId"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/GetProductOverageConfig")]
        [ValidateModelState]
        [SwaggerOperation("GetProductOverageConfig")]
        public virtual IActionResult GetProductOverageConfig([FromQuery][Required()]int? productId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get all products in ApiPayment system
        /// </summary>
        /// <remarks>Retrieve all products available in the ApiPayment system.</remarks>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/Products")]
        [ValidateModelState]
        [SwaggerOperation("GetProducts")]
        public virtual IActionResult GetProducts()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get products family mapping
        /// </summary>
        /// <remarks>Retrieve the mapping of product families.</remarks>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/CCD/ProductsFamilyMapping")]
        [ValidateModelState]
        [SwaggerOperation("GetProductsFamilyMapping")]
        public virtual IActionResult GetProductsFamilyMapping()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Set default customer payment method
        /// </summary>
        /// <remarks>Set the default payment method for a customer identified by email and paymentMethodId.</remarks>
        /// <param name="email"></param>
        /// <param name="paymentMethodId"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/SetDefaultCustomerPaymentMethod")]
        [ValidateModelState]
        [SwaggerOperation("GetSetDefaultCustomerPaymentMethod")]
        public virtual IActionResult GetSetDefaultCustomerPaymentMethod([FromQuery][Required()]string email, [FromQuery][Required()]string paymentMethodId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Show details of a payment method
        /// </summary>
        /// <remarks>Retrieve detailed information about a payment method identified by paymentMethodId.</remarks>
        /// <param name="paymentMethodId"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/ShowPaymentMethodDetails")]
        [ValidateModelState]
        [SwaggerOperation("GetShowPaymentMethodDetails")]
        public virtual IActionResult GetShowPaymentMethodDetails([FromQuery][Required()]string paymentMethodId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get Stripe product price change info
        /// </summary>
        /// <remarks>Retrieve information about a stripe product price change for the specified productPriceId and amount.</remarks>
        /// <param name="productPriceId"></param>
        /// <param name="priceAmount"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/StripeProductPriceChange")]
        [ValidateModelState]
        [SwaggerOperation("GetStripeProductPriceChange")]
        public virtual IActionResult GetStripeProductPriceChange([FromQuery][Required()]string productPriceId, [FromQuery][Required()]int? priceAmount)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get list of Stripe products
        /// </summary>
        /// <remarks>Returns a list of Stripe products available for ApiPayment.</remarks>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/StripeProducts")]
        [ValidateModelState]
        [SwaggerOperation("GetStripeProducts")]
        public virtual IActionResult GetStripeProducts()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get Stripe products for a logged-in user
        /// </summary>
        /// <remarks>Returns a list of Stripe products available for the specified logged-in user identified by email. Optionally includes the resume product when includeResumeProduct is true.</remarks>
        /// <param name="email"></param>
        /// <param name="includeResumeProduct"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/StripeProductsLoggedInUser")]
        [ValidateModelState]
        [SwaggerOperation("GetStripeProductsLoggedInUser")]
        public virtual IActionResult GetStripeProductsLoggedInUser([FromQuery][Required()]string email, [FromQuery]bool? includeResumeProduct)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get subscription payment methods by email
        /// </summary>
        /// <remarks>Retrieve payment methods associated with subscriptions for a customer email.</remarks>
        /// <param name="email"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/GetSubscriptionPaymentMethods")]
        [ValidateModelState]
        [SwaggerOperation("GetSubscriptionPaymentMethods")]
        public virtual IActionResult GetSubscriptionPaymentMethods([FromQuery][Required()]string email)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Get upgrade options for a product and price
        /// </summary>
        /// <remarks>Retrieve available upgrade options for the specified product and price.</remarks>
        /// <param name="productId"></param>
        /// <param name="priceId"></param>
        /// <response code="200">Success</response>
        [HttpGet]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/UpgradeOptions")]
        [ValidateModelState]
        [SwaggerOperation("GetUpgradeOptions")]
        public virtual IActionResult GetUpgradeOptions([FromQuery][Required()]string productId, [FromQuery][Required()]string priceId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Add a customer payment method
        /// </summary>
        /// <remarks>Add a new payment method for a customer identified by email.</remarks>
        /// <param name="email"></param>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/CustomerPaymentMethods")]
        [ValidateModelState]
        [SwaggerOperation("PostCustomerPaymentMethods")]
        public virtual IActionResult PostCustomerPaymentMethods([FromQuery][Required()]string email, [FromBody]AddPaymentMethodRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Suspend or resume subscription by admin
        /// </summary>
        /// <remarks>Suspend or resume an enterprise subscription as an administrator.</remarks>
        /// <param name="subscriptionId"></param>
        /// <param name="action"></param>
        /// <param name="adminEmail"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/Enterprise/SuspendResumeSubscriptionByAdmin")]
        [ValidateModelState]
        [SwaggerOperation("PostEnterpriseSuspendResumeSubscriptionByAdmin")]
        public virtual IActionResult PostEnterpriseSuspendResumeSubscriptionByAdmin([FromQuery][Required()]int? subscriptionId, [FromQuery][Required()]string action, [FromQuery][Required()]string adminEmail)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Pay an invoice
        /// </summary>
        /// <remarks>Pay an invoice identified by invoiceId.</remarks>
        /// <param name="invoiceId"></param>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/InvoicePay")]
        [ValidateModelState]
        [SwaggerOperation("PostInvoicePay")]
        public virtual IActionResult PostInvoicePay([FromQuery][Required()]string invoiceId, [FromBody]InvoicePayRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Search invoices for a subscription
        /// </summary>
        /// <remarks>Search invoices related to a subscription identified by stripeSubscriptionId.</remarks>
        /// <param name="stripeSubscriptionId"></param>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/Invoices")]
        [ValidateModelState]
        [SwaggerOperation("PostInvoices")]
        public virtual IActionResult PostInvoices([FromQuery][Required()]string stripeSubscriptionId, [FromBody]InvoiceSearchRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Resume subscription by admin
        /// </summary>
        /// <remarks>Resume a subscription as an administrator.</remarks>
        /// <param name="stripeSubscriptionId"></param>
        /// <param name="loggedInAdminEmail"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/ResumeSubscriptionByAdmin/{stripeSubscriptionId}/{loggedInAdminEmail}")]
        [ValidateModelState]
        [SwaggerOperation("PostResumeSubscriptionByAdmin")]
        public virtual IActionResult PostResumeSubscriptionByAdmin([FromRoute][Required]string stripeSubscriptionId, [FromRoute][Required]string loggedInAdminEmail)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Post Stripe customer subscriptions by email
        /// </summary>
        /// <remarks>Retrieve Stripe customer subscriptions filtered by email.</remarks>
        /// <param name="email"></param>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/StripeCustomerSubscriptions")]
        [ValidateModelState]
        [SwaggerOperation("PostStripeCustomerSubscriptions")]
        public virtual IActionResult PostStripeCustomerSubscriptions([FromQuery][Required()]string email, [FromBody]SubscriptionSearchRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Suspend subscription by admin
        /// </summary>
        /// <remarks>Suspend a subscription as an administrator.</remarks>
        /// <param name="stripeSubscriptionId"></param>
        /// <param name="loggedInAdminEmail"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/SuspendSubscriptionByAdmin/{stripeSubscriptionId}/{loggedInAdminEmail}")]
        [ValidateModelState]
        [SwaggerOperation("PostSuspendSubscriptionByAdmin")]
        public virtual IActionResult PostSuspendSubscriptionByAdmin([FromRoute][Required]string stripeSubscriptionId, [FromRoute][Required]string loggedInAdminEmail)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Trigger downgrade of a subscription
        /// </summary>
        /// <remarks>Initiate a downgrade process for a subscription identified by stripeSubscriptionId.</remarks>
        /// <param name="stripeSubscriptionId"></param>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/TriggerDowngradeSubscription")]
        [ValidateModelState]
        [SwaggerOperation("PostTriggerDowngradeSubscription")]
        public virtual IActionResult PostTriggerDowngradeSubscription([FromQuery][Required()]string stripeSubscriptionId, [FromBody]UpdateSubscriptionRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Post prorated charge for subscription upgrade
        /// </summary>
        /// <remarks>Calculate and post a prorated charge for upgrading a subscription.</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/UpgradeSubscription/ProratedCharge")]
        [ValidateModelState]
        [SwaggerOperation("PostUpgradeSubscriptionProratedCharge")]
        public virtual IActionResult PostUpgradeSubscriptionProratedCharge([FromBody]UpgradeSubscriptionProratedChargeRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Cancel a subscription
        /// </summary>
        /// <remarks>Cancel a subscription identified by stripeSubscriptionId.</remarks>
        /// <param name="stripeSubscriptionId"></param>
        /// <response code="200">Success</response>
        [HttpPut]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/CancelSubscription")]
        [ValidateModelState]
        [SwaggerOperation("PutCancelSubscription")]
        public virtual IActionResult PutCancelSubscription([FromQuery][Required()]string stripeSubscriptionId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Change payment method for a subscription
        /// </summary>
        /// <remarks>Change the payment method for a subscription identified by stripeSubscriptionId.</remarks>
        /// <param name="stripeSubscriptionId"></param>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPut]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/ChangeSubscriptionPaymentMethod")]
        [ValidateModelState]
        [SwaggerOperation("PutChangeSubscriptionPaymentMethod")]
        public virtual IActionResult PutChangeSubscriptionPaymentMethod([FromQuery][Required()]string stripeSubscriptionId, [FromBody]SubscriptionPaymentMethodRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Downgrade a subscription
        /// </summary>
        /// <remarks>Downgrade an existing subscription identified by stripeSubscriptionId.</remarks>
        /// <param name="stripeSubscriptionId"></param>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPut]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/DowngradeSubscription")]
        [ValidateModelState]
        [SwaggerOperation("PutDowngradeSubscription")]
        public virtual IActionResult PutDowngradeSubscription([FromQuery][Required()]string stripeSubscriptionId, [FromBody]UpdateSubscriptionRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Downgrade enterprise subscription
        /// </summary>
        /// <remarks>Downgrade an enterprise subscription with new product price.</remarks>
        /// <param name="email"></param>
        /// <param name="currentStripeProductPriceId"></param>
        /// <param name="newStripeProductPriceId"></param>
        /// <response code="200">Success</response>
        [HttpPut]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/Enterprise/DowngradeSubscription")]
        [ValidateModelState]
        [SwaggerOperation("PutEnterpriseDowngradeSubscription")]
        public virtual IActionResult PutEnterpriseDowngradeSubscription([FromQuery][Required()]string email, [FromQuery][Required()]string currentStripeProductPriceId, [FromQuery][Required()]string newStripeProductPriceId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Upgrade enterprise subscription
        /// </summary>
        /// <remarks>Upgrade an enterprise subscription with new product price.</remarks>
        /// <param name="email"></param>
        /// <param name="currentStripeProductPriceId"></param>
        /// <param name="newStripeProductPriceId"></param>
        /// <response code="200">Success</response>
        [HttpPut]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/Enterprise/UpgradeSubscription")]
        [ValidateModelState]
        [SwaggerOperation("PutEnterpriseUpgradeSubscription")]
        public virtual IActionResult PutEnterpriseUpgradeSubscription([FromQuery][Required()]string email, [FromQuery][Required()]string currentStripeProductPriceId, [FromQuery][Required()]string newStripeProductPriceId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Update a customer payment method
        /// </summary>
        /// <remarks>Update an existing customer payment method identified by paymentMethodId.</remarks>
        /// <param name="paymentMethodId"></param>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPut]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/UpdateCustomerPaymentMethods")]
        [ValidateModelState]
        [SwaggerOperation("PutUpdateCustomerPaymentMethods")]
        public virtual IActionResult PutUpdateCustomerPaymentMethods([FromQuery][Required()]string paymentMethodId, [FromBody]UpdatePaymentMethodRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Upgrade a subscription
        /// </summary>
        /// <remarks>Upgrade an existing subscription identified by stripeSubscriptionId.</remarks>
        /// <param name="stripeSubscriptionId"></param>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPut]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/UpgradeSubscription")]
        [ValidateModelState]
        [SwaggerOperation("PutUpgradeSubscription")]
        public virtual IActionResult PutUpgradeSubscription([FromQuery][Required()]string stripeSubscriptionId, [FromBody]UpdateSubscriptionRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Save product overage configuration
        /// </summary>
        /// <remarks>Save or update the product overage configuration for ApiPayment. Accepts a ProductOverageConfig payload.</remarks>
        /// <param name="body"></param>
        /// <response code="200">Success</response>
        [HttpPost]
        [Route("/cjoshi-dev/ApiPayment/v1/ApiPayment/v1/SaveProductOverageConfig")]
        [ValidateModelState]
        [SwaggerOperation("SaveProductOverageConfig")]
        public virtual IActionResult SaveProductOverageConfig([FromBody]ProductOverageConfig body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            throw new NotImplementedException();
        }
    }
}
