/*
 * ApiPayment API
 *
 * API for handling payments, subscriptions, invoices, and payment methods for ApiPayment services.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AddPaymentMethodRequest : IEquatable<AddPaymentMethodRequest>
    { 
        /// <summary>
        /// Gets or Sets AppCode
        /// </summary>

        [DataMember(Name="AppCode")]
        public string AppCode { get; set; }

        /// <summary>
        /// Gets or Sets SuccessUrl
        /// </summary>

        [DataMember(Name="SuccessUrl")]
        public string SuccessUrl { get; set; }

        /// <summary>
        /// Gets or Sets CancelUrl
        /// </summary>

        [DataMember(Name="CancelUrl")]
        public string CancelUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddPaymentMethodRequest {\n");
            sb.Append("  AppCode: ").Append(AppCode).Append("\n");
            sb.Append("  SuccessUrl: ").Append(SuccessUrl).Append("\n");
            sb.Append("  CancelUrl: ").Append(CancelUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AddPaymentMethodRequest)obj);
        }

        /// <summary>
        /// Returns true if AddPaymentMethodRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of AddPaymentMethodRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddPaymentMethodRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AppCode == other.AppCode ||
                    AppCode != null &&
                    AppCode.Equals(other.AppCode)
                ) && 
                (
                    SuccessUrl == other.SuccessUrl ||
                    SuccessUrl != null &&
                    SuccessUrl.Equals(other.SuccessUrl)
                ) && 
                (
                    CancelUrl == other.CancelUrl ||
                    CancelUrl != null &&
                    CancelUrl.Equals(other.CancelUrl)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (AppCode != null)
                    hashCode = hashCode * 59 + AppCode.GetHashCode();
                    if (SuccessUrl != null)
                    hashCode = hashCode * 59 + SuccessUrl.GetHashCode();
                    if (CancelUrl != null)
                    hashCode = hashCode * 59 + CancelUrl.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(AddPaymentMethodRequest left, AddPaymentMethodRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AddPaymentMethodRequest left, AddPaymentMethodRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
