/*
 * ApiPayment API
 *
 * API for handling payments, subscriptions, invoices, and payment methods for ApiPayment services.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DateRangeFilter : IEquatable<DateRangeFilter>
    { 
        /// <summary>
        /// Gets or Sets GreaterThanOrEqual
        /// </summary>

        [DataMember(Name="GreaterThanOrEqual")]
        public DateTime? GreaterThanOrEqual { get; set; }

        /// <summary>
        /// Gets or Sets LessThanOrEqual
        /// </summary>

        [DataMember(Name="LessThanOrEqual")]
        public DateTime? LessThanOrEqual { get; set; }

        /// <summary>
        /// Gets or Sets LessThan
        /// </summary>

        [DataMember(Name="LessThan")]
        public DateTime? LessThan { get; set; }

        /// <summary>
        /// Gets or Sets GreaterThan
        /// </summary>

        [DataMember(Name="GreaterThan")]
        public DateTime? GreaterThan { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DateRangeFilter {\n");
            sb.Append("  GreaterThanOrEqual: ").Append(GreaterThanOrEqual).Append("\n");
            sb.Append("  LessThanOrEqual: ").Append(LessThanOrEqual).Append("\n");
            sb.Append("  LessThan: ").Append(LessThan).Append("\n");
            sb.Append("  GreaterThan: ").Append(GreaterThan).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DateRangeFilter)obj);
        }

        /// <summary>
        /// Returns true if DateRangeFilter instances are equal
        /// </summary>
        /// <param name="other">Instance of DateRangeFilter to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DateRangeFilter other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    GreaterThanOrEqual == other.GreaterThanOrEqual ||
                    GreaterThanOrEqual != null &&
                    GreaterThanOrEqual.Equals(other.GreaterThanOrEqual)
                ) && 
                (
                    LessThanOrEqual == other.LessThanOrEqual ||
                    LessThanOrEqual != null &&
                    LessThanOrEqual.Equals(other.LessThanOrEqual)
                ) && 
                (
                    LessThan == other.LessThan ||
                    LessThan != null &&
                    LessThan.Equals(other.LessThan)
                ) && 
                (
                    GreaterThan == other.GreaterThan ||
                    GreaterThan != null &&
                    GreaterThan.Equals(other.GreaterThan)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (GreaterThanOrEqual != null)
                    hashCode = hashCode * 59 + GreaterThanOrEqual.GetHashCode();
                    if (LessThanOrEqual != null)
                    hashCode = hashCode * 59 + LessThanOrEqual.GetHashCode();
                    if (LessThan != null)
                    hashCode = hashCode * 59 + LessThan.GetHashCode();
                    if (GreaterThan != null)
                    hashCode = hashCode * 59 + GreaterThan.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DateRangeFilter left, DateRangeFilter right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DateRangeFilter left, DateRangeFilter right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
