/*
 * ApiPayment API
 *
 * API for handling payments, subscriptions, invoices, and payment methods for ApiPayment services.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InvoiceSearchRequest : IEquatable<InvoiceSearchRequest>
    { 
        /// <summary>
        /// Gets or Sets Limit
        /// </summary>

        [DataMember(Name="Limit")]
        public int? Limit { get; set; }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>

        [DataMember(Name="Created")]
        public DateRangeFilter Created { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceStatus
        /// </summary>

        [DataMember(Name="invoiceStatus")]
        public InvoiceStatus InvoiceStatus { get; set; }

        /// <summary>
        /// Gets or Sets Customer
        /// </summary>

        [DataMember(Name="Customer")]
        public string Customer { get; set; }

        /// <summary>
        /// Gets or Sets CollectionMethod
        /// </summary>

        [DataMember(Name="CollectionMethod")]
        public string CollectionMethod { get; set; }

        /// <summary>
        /// Gets or Sets DueDate
        /// </summary>

        [DataMember(Name="DueDate")]
        public DateRangeFilter DueDate { get; set; }

        /// <summary>
        /// Gets or Sets EndingBefore
        /// </summary>

        [DataMember(Name="EndingBefore")]
        public string EndingBefore { get; set; }

        /// <summary>
        /// Gets or Sets StartingAfter
        /// </summary>

        [DataMember(Name="StartingAfter")]
        public string StartingAfter { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InvoiceSearchRequest {\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  InvoiceStatus: ").Append(InvoiceStatus).Append("\n");
            sb.Append("  Customer: ").Append(Customer).Append("\n");
            sb.Append("  CollectionMethod: ").Append(CollectionMethod).Append("\n");
            sb.Append("  DueDate: ").Append(DueDate).Append("\n");
            sb.Append("  EndingBefore: ").Append(EndingBefore).Append("\n");
            sb.Append("  StartingAfter: ").Append(StartingAfter).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InvoiceSearchRequest)obj);
        }

        /// <summary>
        /// Returns true if InvoiceSearchRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of InvoiceSearchRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InvoiceSearchRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Limit == other.Limit ||
                    Limit != null &&
                    Limit.Equals(other.Limit)
                ) && 
                (
                    Created == other.Created ||
                    Created != null &&
                    Created.Equals(other.Created)
                ) && 
                (
                    InvoiceStatus == other.InvoiceStatus ||
                    InvoiceStatus != null &&
                    InvoiceStatus.Equals(other.InvoiceStatus)
                ) && 
                (
                    Customer == other.Customer ||
                    Customer != null &&
                    Customer.Equals(other.Customer)
                ) && 
                (
                    CollectionMethod == other.CollectionMethod ||
                    CollectionMethod != null &&
                    CollectionMethod.Equals(other.CollectionMethod)
                ) && 
                (
                    DueDate == other.DueDate ||
                    DueDate != null &&
                    DueDate.Equals(other.DueDate)
                ) && 
                (
                    EndingBefore == other.EndingBefore ||
                    EndingBefore != null &&
                    EndingBefore.Equals(other.EndingBefore)
                ) && 
                (
                    StartingAfter == other.StartingAfter ||
                    StartingAfter != null &&
                    StartingAfter.Equals(other.StartingAfter)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Limit != null)
                    hashCode = hashCode * 59 + Limit.GetHashCode();
                    if (Created != null)
                    hashCode = hashCode * 59 + Created.GetHashCode();
                    if (InvoiceStatus != null)
                    hashCode = hashCode * 59 + InvoiceStatus.GetHashCode();
                    if (Customer != null)
                    hashCode = hashCode * 59 + Customer.GetHashCode();
                    if (CollectionMethod != null)
                    hashCode = hashCode * 59 + CollectionMethod.GetHashCode();
                    if (DueDate != null)
                    hashCode = hashCode * 59 + DueDate.GetHashCode();
                    if (EndingBefore != null)
                    hashCode = hashCode * 59 + EndingBefore.GetHashCode();
                    if (StartingAfter != null)
                    hashCode = hashCode * 59 + StartingAfter.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InvoiceSearchRequest left, InvoiceSearchRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InvoiceSearchRequest left, InvoiceSearchRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
