/*
 * ApiPayment API
 *
 * API for handling payments, subscriptions, invoices, and payment methods for ApiPayment services.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ProductOverageConfig : IEquatable<ProductOverageConfig>
    { 
        /// <summary>
        /// Gets or Sets Id
        /// </summary>

        [DataMember(Name="Id")]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets ProductId
        /// </summary>
        [Required]

        [Range(1, 999999999)]
        [DataMember(Name="ProductId")]
        public int? ProductId { get; set; }

        /// <summary>
        /// Gets or Sets NumberOfRequest
        /// </summary>
        [Required]

        [Range(1, 1000000)]
        [DataMember(Name="NumberOfRequest")]
        public int? NumberOfRequest { get; set; }

        /// <summary>
        /// Gets or Sets Rate
        /// </summary>
        [Required]

        [DataMember(Name="Rate")]
        public double? Rate { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>

        [DataMember(Name="IsActive")]
        public string IsActive { get; set; }

        /// <summary>
        /// Gets or Sets CreatedDateTime
        /// </summary>

        [DataMember(Name="CreatedDateTime")]
        public DateTime? CreatedDateTime { get; set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>

        [DataMember(Name="CreatedBy")]
        public string CreatedBy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductOverageConfig {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ProductId: ").Append(ProductId).Append("\n");
            sb.Append("  NumberOfRequest: ").Append(NumberOfRequest).Append("\n");
            sb.Append("  Rate: ").Append(Rate).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  CreatedDateTime: ").Append(CreatedDateTime).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ProductOverageConfig)obj);
        }

        /// <summary>
        /// Returns true if ProductOverageConfig instances are equal
        /// </summary>
        /// <param name="other">Instance of ProductOverageConfig to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductOverageConfig other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    ProductId == other.ProductId ||
                    ProductId != null &&
                    ProductId.Equals(other.ProductId)
                ) && 
                (
                    NumberOfRequest == other.NumberOfRequest ||
                    NumberOfRequest != null &&
                    NumberOfRequest.Equals(other.NumberOfRequest)
                ) && 
                (
                    Rate == other.Rate ||
                    Rate != null &&
                    Rate.Equals(other.Rate)
                ) && 
                (
                    IsActive == other.IsActive ||
                    IsActive != null &&
                    IsActive.Equals(other.IsActive)
                ) && 
                (
                    CreatedDateTime == other.CreatedDateTime ||
                    CreatedDateTime != null &&
                    CreatedDateTime.Equals(other.CreatedDateTime)
                ) && 
                (
                    CreatedBy == other.CreatedBy ||
                    CreatedBy != null &&
                    CreatedBy.Equals(other.CreatedBy)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (ProductId != null)
                    hashCode = hashCode * 59 + ProductId.GetHashCode();
                    if (NumberOfRequest != null)
                    hashCode = hashCode * 59 + NumberOfRequest.GetHashCode();
                    if (Rate != null)
                    hashCode = hashCode * 59 + Rate.GetHashCode();
                    if (IsActive != null)
                    hashCode = hashCode * 59 + IsActive.GetHashCode();
                    if (CreatedDateTime != null)
                    hashCode = hashCode * 59 + CreatedDateTime.GetHashCode();
                    if (CreatedBy != null)
                    hashCode = hashCode * 59 + CreatedBy.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ProductOverageConfig left, ProductOverageConfig right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductOverageConfig left, ProductOverageConfig right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
