/*
 * ApiPayment API
 *
 * API for handling payments, subscriptions, invoices, and payment methods for ApiPayment services.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SubscriptionSearchRequest : IEquatable<SubscriptionSearchRequest>
    { 
        /// <summary>
        /// Gets or Sets Status
        /// </summary>

        [DataMember(Name="Status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>

        [DataMember(Name="Created")]
        public DateRangeFilter Created { get; set; }

        /// <summary>
        /// Gets or Sets EndingBefore
        /// </summary>

        [DataMember(Name="EndingBefore")]
        public string EndingBefore { get; set; }

        /// <summary>
        /// Gets or Sets StartingAfter
        /// </summary>

        [DataMember(Name="StartingAfter")]
        public string StartingAfter { get; set; }

        /// <summary>
        /// Gets or Sets Limit
        /// </summary>

        [DataMember(Name="Limit")]
        public int? Limit { get; set; }

        /// <summary>
        /// Gets or Sets Price
        /// </summary>

        [DataMember(Name="Price")]
        public string Price { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubscriptionSearchRequest {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  EndingBefore: ").Append(EndingBefore).Append("\n");
            sb.Append("  StartingAfter: ").Append(StartingAfter).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SubscriptionSearchRequest)obj);
        }

        /// <summary>
        /// Returns true if SubscriptionSearchRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of SubscriptionSearchRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubscriptionSearchRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                ) && 
                (
                    Created == other.Created ||
                    Created != null &&
                    Created.Equals(other.Created)
                ) && 
                (
                    EndingBefore == other.EndingBefore ||
                    EndingBefore != null &&
                    EndingBefore.Equals(other.EndingBefore)
                ) && 
                (
                    StartingAfter == other.StartingAfter ||
                    StartingAfter != null &&
                    StartingAfter.Equals(other.StartingAfter)
                ) && 
                (
                    Limit == other.Limit ||
                    Limit != null &&
                    Limit.Equals(other.Limit)
                ) && 
                (
                    Price == other.Price ||
                    Price != null &&
                    Price.Equals(other.Price)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (Created != null)
                    hashCode = hashCode * 59 + Created.GetHashCode();
                    if (EndingBefore != null)
                    hashCode = hashCode * 59 + EndingBefore.GetHashCode();
                    if (StartingAfter != null)
                    hashCode = hashCode * 59 + StartingAfter.GetHashCode();
                    if (Limit != null)
                    hashCode = hashCode * 59 + Limit.GetHashCode();
                    if (Price != null)
                    hashCode = hashCode * 59 + Price.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SubscriptionSearchRequest left, SubscriptionSearchRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SubscriptionSearchRequest left, SubscriptionSearchRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
