/*
 * ApiPayment API
 *
 * API for handling payments, subscriptions, invoices, and payment methods for ApiPayment services.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class SubscriptionRequest : IEquatable<SubscriptionRequest>
    { 
        /// <summary>
        /// Gets or Sets AppCode
        /// </summary>

        [DataMember(Name="AppCode")]
        public string AppCode { get; set; }

        /// <summary>
        /// Gets or Sets PriceId
        /// </summary>
        [Required]

        [MinLength(1)]
        [DataMember(Name="PriceId")]
        public string PriceId { get; set; }

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>

        [DataMember(Name="CustomerId")]
        public string CustomerId { get; set; }

        /// <summary>
        /// Gets or Sets CustomerEmail
        /// </summary>

        [DataMember(Name="CustomerEmail")]
        public string CustomerEmail { get; set; }

        /// <summary>
        /// Gets or Sets SuccessUrl
        /// </summary>

        [DataMember(Name="SuccessUrl")]
        public string SuccessUrl { get; set; }

        /// <summary>
        /// Gets or Sets CancelUrl
        /// </summary>

        [DataMember(Name="CancelUrl")]
        public string CancelUrl { get; set; }

        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>

        [DataMember(Name="Quantity")]
        public int? Quantity { get; set; }

        /// <summary>
        /// Gets or Sets TrialPeriodDays
        /// </summary>

        [DataMember(Name="TrialPeriodDays")]
        public int? TrialPeriodDays { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubscriptionRequest {\n");
            sb.Append("  AppCode: ").Append(AppCode).Append("\n");
            sb.Append("  PriceId: ").Append(PriceId).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  CustomerEmail: ").Append(CustomerEmail).Append("\n");
            sb.Append("  SuccessUrl: ").Append(SuccessUrl).Append("\n");
            sb.Append("  CancelUrl: ").Append(CancelUrl).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("  TrialPeriodDays: ").Append(TrialPeriodDays).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SubscriptionRequest)obj);
        }

        /// <summary>
        /// Returns true if SubscriptionRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of SubscriptionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubscriptionRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AppCode == other.AppCode ||
                    AppCode != null &&
                    AppCode.Equals(other.AppCode)
                ) && 
                (
                    PriceId == other.PriceId ||
                    PriceId != null &&
                    PriceId.Equals(other.PriceId)
                ) && 
                (
                    CustomerId == other.CustomerId ||
                    CustomerId != null &&
                    CustomerId.Equals(other.CustomerId)
                ) && 
                (
                    CustomerEmail == other.CustomerEmail ||
                    CustomerEmail != null &&
                    CustomerEmail.Equals(other.CustomerEmail)
                ) && 
                (
                    SuccessUrl == other.SuccessUrl ||
                    SuccessUrl != null &&
                    SuccessUrl.Equals(other.SuccessUrl)
                ) && 
                (
                    CancelUrl == other.CancelUrl ||
                    CancelUrl != null &&
                    CancelUrl.Equals(other.CancelUrl)
                ) && 
                (
                    Quantity == other.Quantity ||
                    Quantity != null &&
                    Quantity.Equals(other.Quantity)
                ) && 
                (
                    TrialPeriodDays == other.TrialPeriodDays ||
                    TrialPeriodDays != null &&
                    TrialPeriodDays.Equals(other.TrialPeriodDays)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (AppCode != null)
                    hashCode = hashCode * 59 + AppCode.GetHashCode();
                    if (PriceId != null)
                    hashCode = hashCode * 59 + PriceId.GetHashCode();
                    if (CustomerId != null)
                    hashCode = hashCode * 59 + CustomerId.GetHashCode();
                    if (CustomerEmail != null)
                    hashCode = hashCode * 59 + CustomerEmail.GetHashCode();
                    if (SuccessUrl != null)
                    hashCode = hashCode * 59 + SuccessUrl.GetHashCode();
                    if (CancelUrl != null)
                    hashCode = hashCode * 59 + CancelUrl.GetHashCode();
                    if (Quantity != null)
                    hashCode = hashCode * 59 + Quantity.GetHashCode();
                    if (TrialPeriodDays != null)
                    hashCode = hashCode * 59 + TrialPeriodDays.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SubscriptionRequest left, SubscriptionRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SubscriptionRequest left, SubscriptionRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
