/*
 * ApiPayment API
 *
 * API for handling payments, subscriptions, invoices, and payment methods for ApiPayment services.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class UpdatePaymentMethodRequest : IEquatable<UpdatePaymentMethodRequest>
    { 
        /// <summary>
        /// Gets or Sets BillingDetails
        /// </summary>

        [DataMember(Name="billing_details")]
        public BillingDetails BillingDetails { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>

        [DataMember(Name="metadata")]
        public PaymentMethodMetadata Metadata { get; set; }

        /// <summary>
        /// Gets or Sets Card
        /// </summary>

        [DataMember(Name="card")]
        public Card Card { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpdatePaymentMethodRequest {\n");
            sb.Append("  BillingDetails: ").Append(BillingDetails).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  Card: ").Append(Card).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UpdatePaymentMethodRequest)obj);
        }

        /// <summary>
        /// Returns true if UpdatePaymentMethodRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of UpdatePaymentMethodRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdatePaymentMethodRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    BillingDetails == other.BillingDetails ||
                    BillingDetails != null &&
                    BillingDetails.Equals(other.BillingDetails)
                ) && 
                (
                    Metadata == other.Metadata ||
                    Metadata != null &&
                    Metadata.Equals(other.Metadata)
                ) && 
                (
                    Card == other.Card ||
                    Card != null &&
                    Card.Equals(other.Card)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (BillingDetails != null)
                    hashCode = hashCode * 59 + BillingDetails.GetHashCode();
                    if (Metadata != null)
                    hashCode = hashCode * 59 + Metadata.GetHashCode();
                    if (Card != null)
                    hashCode = hashCode * 59 + Card.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UpdatePaymentMethodRequest left, UpdatePaymentMethodRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UpdatePaymentMethodRequest left, UpdatePaymentMethodRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
