/*
 * ApiPayment API
 *
 * API for handling payments, subscriptions, invoices, and payment methods for ApiPayment services.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class UpgradeSubscriptionProratedChargeRequest : IEquatable<UpgradeSubscriptionProratedChargeRequest>
    { 
        /// <summary>
        /// Gets or Sets StripeSubscriptionId
        /// </summary>

        [DataMember(Name="stripeSubscriptionId")]
        public string StripeSubscriptionId { get; set; }

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>

        [DataMember(Name="customerId")]
        public string CustomerId { get; set; }

        /// <summary>
        /// Gets or Sets NewUpgradePriceId
        /// </summary>

        [DataMember(Name="newUpgradePriceId")]
        public string NewUpgradePriceId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UpgradeSubscriptionProratedChargeRequest {\n");
            sb.Append("  StripeSubscriptionId: ").Append(StripeSubscriptionId).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  NewUpgradePriceId: ").Append(NewUpgradePriceId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UpgradeSubscriptionProratedChargeRequest)obj);
        }

        /// <summary>
        /// Returns true if UpgradeSubscriptionProratedChargeRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of UpgradeSubscriptionProratedChargeRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpgradeSubscriptionProratedChargeRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    StripeSubscriptionId == other.StripeSubscriptionId ||
                    StripeSubscriptionId != null &&
                    StripeSubscriptionId.Equals(other.StripeSubscriptionId)
                ) && 
                (
                    CustomerId == other.CustomerId ||
                    CustomerId != null &&
                    CustomerId.Equals(other.CustomerId)
                ) && 
                (
                    NewUpgradePriceId == other.NewUpgradePriceId ||
                    NewUpgradePriceId != null &&
                    NewUpgradePriceId.Equals(other.NewUpgradePriceId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (StripeSubscriptionId != null)
                    hashCode = hashCode * 59 + StripeSubscriptionId.GetHashCode();
                    if (CustomerId != null)
                    hashCode = hashCode * 59 + CustomerId.GetHashCode();
                    if (NewUpgradePriceId != null)
                    hashCode = hashCode * 59 + NewUpgradePriceId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UpgradeSubscriptionProratedChargeRequest left, UpgradeSubscriptionProratedChargeRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UpgradeSubscriptionProratedChargeRequest left, UpgradeSubscriptionProratedChargeRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
